<footer class="footer" style="background-color: #212529;">
    <div class="container pt-3">
        <div class="container rounded-pill p-3 my-5 bg-white text-dark">
            <div class="row ms-auto text-center">
                <div class="col-sm-12 col-xs-12 col-md-12 col-lg-4 text-center">
                    <img src="images/map-icon.png">
                    <span class="londan_text">London 145 United Kingdom</span>
                </div>
                <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4 text-center">
                    <img src="images/phone-icon.png">
                    <span class="london_text">+7586656566</span>
                </div>
                <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4 text-center">
                    <div class="map_main">
                        <img src="images/email-icon.png">
                        <span class="london_text">demo@gmail.com</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row text-dark">
            <div class="col-sm-6 col-md-6 col-lg-2 ">
                <div class="footer-logo bg-light rounded-pill p-3 text-dark text-center"><img src="images/logo.png"
                                                                                              style="max-width: 100%;">
                    <h5 class="fw-bolder d-inline m">WEBHOS</h5>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-2">
                <h5 class="useful_text">USEFUL LINKS</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#home"><img
                                    src="images/bullet-icon.png" style="padding-right: 10px;">Home</a></li>
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#about"><img
                                    src="images/bullet-icon.png" style="padding-right: 10px;">About</a></li>
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#service"><img
                                    src="images/bullet-icon.png" style="padding-right: 10px;">Services</a></li>
                    <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#contact"><img
                                    src="images/bullet-icon.png" style="padding-right: 10px;">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-2">
                <h5 class="useful_text">PRODUCT</h5>
                <div class="contaienr">
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#"><img
                                        src="images/bullet-icon.png" class="">Webhosting</a></li>
                        <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#"><img
                                        src="images/bullet-icon.png" class="nav-item mb-2">Reseller Hosting</a></li>
                        <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#"><img
                                        src="images/bullet-icon.png" class="nav-item mb-2">VPS Hosting</a></li>
                        <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#"><img
                                        src="images/bullet-icon.png" class="nav-item mb-2">Wordpress Hosting</a></li>
                        <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#"><img
                                        src="images/bullet-icon.png" class="nav-item mb-2">Dedicated hosting</a></li>
                        <li class="nav-item mb-2"><a class="nav-link p-0 text-white" href="#"><img
                                        src="images/bullet-icon.png" class="nav-item mb-2">Windows</a></li>
                    </ul>
                </div>

            </div>
            <div class="col-sm-12 col-md-12 col-lg-6">
                <h5 class="display-7">Subscribe to our newsletter for the latest news and offers!</h5>
                <form action="" class="input-group mb-3 " method="GET">
                    <input type="email" class="form-control" placeholder="Enter your email" name="subscriber_email"
                           required>
                    <div class="input-group-append">
                        <button class="btn btn-success" type="submit"><a class="text-decoration-none text-white "
                                                                         href="">SUBSCRIBE</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="  px-5 border-top text-center d-flex justify-content-between bg-success text-light">
        <p class="text">© 2022 All Rights Reserved</p>
        <ul class="list-unstyled d-flex justify-content-center">
            <li class="ms-3"><a class="link-dark text-primary" href="#"><img width="20px" height="40px"
                                                                             src=" images/5296499_fb_facebook_facebook logo_icon.svg"
                                                                             alt="facebook"></a></li>
            <li class="ms-3"><a class="link-dark text-danger" href="#"><img width="20px" height="40px"
                                                                            src=" images/5296514_bird_tweet_twitter_twitter logo_icon.svg"
                                                                            alt="twitter"></a></li>
            <li class="ms-3"><a class="link-dark text-info" href="#"><img width="20px" height="40px"
                                                                          src=" images/5296765_camera_instagram_instagram logo_icon.svg"
                                                                          alt="instagram"></a></li>
        </ul>
    </div>
</footer>

