<?php

namespace app\models;

use app\core\Application;
use app\core\ProfileModel;

class Profile extends ProfileModel
{
    const DEFAULT_IMG = 0;
    public int $img_id = 0;
    public int $user_id = 0;
    public int $setting_id = 0;

    public function tableName(): string
    {
        return 'user_settings';
    }

    public function attributes(): array
    {
        return ['setting_id', 'user_id', 'img_id',];
    }

    public function primaryKey(): string
    {
        return "setting_id";
    }

    public function rules(): array
    {
        return [
            'user_id' => [self::RULE_REQUIRED]
        ];
    }

    public function save()
    {
        $this->setting_id = random_int(99999, 14124141);
        return parent::save(); // TODO: Change the autogenerated stub
    }
}